package fr.GalileeGFormation.entites;
// Generated 9 mars 2016 21:41:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cours generated by hbm2java
 */
@Entity
@Table(name="cours"
    ,catalog="formation_db"
)
public class Cours  implements java.io.Serializable {


     private Integer coursId;
     private Users users;
     private String libelle;
     private String abreviation;
     private String description;
     private byte[] document;
     private Set<Formation> formations = new HashSet<Formation>(0);

    public Cours() {
    }

    public Cours(String libelle, String abreviation, String description) {
        this.libelle = libelle;
        this.abreviation = abreviation;
        this.description = description;
    }

    public Cours(Users users) {
        this.users = users;
    }
    public Cours(Users users, String libelle, String abreviation, String description, byte[] document, Set<Formation> formations) {
       this.users = users;
       this.libelle = libelle;
       this.abreviation = abreviation;
       this.description = description;
       this.document = document;
       this.formations = formations;
    }
   
    @Id 
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="coursId", unique=true, nullable=false)
    public Integer getCoursId() {
        return coursId;
    }

    public void setCoursId(Integer coursId) {
        this.coursId = coursId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", nullable=false)
    public Users getUsers() {
        return this.users;
    }

    
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="libelle", length=150)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="abreviation", length=20)
    public String getAbreviation() {
        return this.abreviation;
    }
    
    public void setAbreviation(String abreviation) {
        this.abreviation = abreviation;
    }

    
    @Column(name="description", length=16777215)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="document")
    public byte[] getDocument() {
        return this.document;
    }
    
    public void setDocument(byte[] document) {
        this.document = document;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="courses")
    public Set<Formation> getFormations() {
        return this.formations;
    }
    
    public void setFormations(Set<Formation> formations) {
        this.formations = formations;
    }

    @Override
    public String toString() {
        return "Cours{" + "libelle=" + libelle + '}';
    }

    

    
}


