package fr.GalileeGFormation.entites;
// Generated 9 mars 2016 21:41:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Departement generated by hbm2java
 */
@Entity
@Table(name="departement"
    ,catalog="formation_db"
)
public class Departement  implements java.io.Serializable {


     private Integer departementId;
     private Secretariat secretariat;
     private Users users;
     private String libelle;
     private String abreviation;
     private String description;
     private byte[] document;
     private Set<Composante> composantes = new HashSet<Composante>(0);
     private Set<SuperFormation> superFormations = new HashSet<SuperFormation>(0);

    public Departement() {
    }

    public Departement(String libelle, String abreviation, String description) {
        this.libelle = libelle;
        this.abreviation = abreviation;
        this.description = description;
    }

    public Departement(Secretariat secretariat, Users users) {
        this.secretariat = secretariat;
        this.users = users;
    }
    public Departement(Secretariat secretariat, Users users, String libelle, String abreviation, String description, byte[] document, Set<Composante> composantes, Set<SuperFormation> superFormations) {
       this.secretariat = secretariat;
       this.users = users;
       this.libelle = libelle;
       this.abreviation = abreviation;
       this.description = description;
       this.document = document;
       this.composantes = composantes;
       this.superFormations = superFormations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="departementId", unique=true, nullable=false)
    public Integer getDepartementId() {
        return this.departementId;
    }
    
    public void setDepartementId(Integer departementId) {
        this.departementId = departementId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="secretariatId", nullable=false)
    public Secretariat getSecretariat() {
        return this.secretariat;
    }
    
    public void setSecretariat(Secretariat secretariat) {
        this.secretariat = secretariat;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="libelle", length=150)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="abreviation", length=20)
    public String getAbreviation() {
        return this.abreviation;
    }
    
    public void setAbreviation(String abreviation) {
        this.abreviation = abreviation;
    }

    
    @Column(name="description", length=16777215)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="document")
    public byte[] getDocument() {
        return this.document;
    }
    
    public void setDocument(byte[] document) {
        this.document = document;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="departements")
    public Set<Composante> getComposantes() {
        return this.composantes;
    }
    
    public void setComposantes(Set<Composante> composantes) {
        this.composantes = composantes;
    }

@ManyToMany(fetch=FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinTable(name="departement_superformation", catalog="formation_db", joinColumns = { 
        @JoinColumn(name="departementId", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="supformationId", nullable=false, updatable=false) })
    public Set<SuperFormation> getSuperFormations() {
        return this.superFormations;
    }
    
    public void setSuperFormations(Set<SuperFormation> superFormations) {
        this.superFormations = superFormations;
    }

    @Override
    public String toString() {
        return "Departement{" + "libelle=" + libelle + '}';
    }

    
}


