package fr.GalileeGFormation.entites;
// Generated 9 mars 2016 21:41:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Formation generated by hbm2java
 */
@Entity
@Table(name="formation"
    ,catalog="formation_db"
)
public class Formation  implements java.io.Serializable {


     private Integer formationId;
     private Secretariat secretariat;
     private Users users;
     private String libelle;
     private String abreviation;
     private String description;
     private byte[] document;
     private Set<Cours> courses = new HashSet<Cours>(0);
     private Set<SuperFormation> superFormations = new HashSet<SuperFormation>(0);

    public Formation() {
    }

    public Formation(String libelle, String abreviation, String description) {
        this.libelle = libelle;
        this.abreviation = abreviation;
        this.description = description;
    }

    public Formation(Secretariat secretariat, Users users) {
        this.secretariat = secretariat;
        this.users = users;
    }
    public Formation(Secretariat secretariat, Users users, String libelle, String abreviation, String description, byte[] document, Set<Cours> courses, Set<SuperFormation> superFormations) {
       this.secretariat = secretariat;
       this.users = users;
       this.libelle = libelle;
       this.abreviation = abreviation;
       this.description = description;
       this.document = document;
       this.courses = courses;
       this.superFormations = superFormations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="formationId", unique=true, nullable=false)
    public Integer getFormationId() {
        return this.formationId;
    }
    
    public void setFormationId(Integer formationId) {
        this.formationId = formationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="secretariatId", nullable=false)
    public Secretariat getSecretariat() {
        return this.secretariat;
    }
    
    public void setSecretariat(Secretariat secretariat) {
        this.secretariat = secretariat;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="libelle", length=150)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="abreviation", length=20)
    public String getAbreviation() {
        return this.abreviation;
    }
    
    public void setAbreviation(String abreviation) {
        this.abreviation = abreviation;
    }

    
    @Column(name="description", length=16777215)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="document")
    public byte[] getDocument() {
        return this.document;
    }
    
    public void setDocument(byte[] document) {
        this.document = document;
    }

@ManyToMany(fetch=FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinTable(name="formation_cours", catalog="formation_db", joinColumns = { 
        @JoinColumn(name="formationId", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="coursId", nullable=false, updatable=false) })
    public Set<Cours> getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set<Cours> courses) {
        this.courses = courses;
    }

    
    
@ManyToMany(fetch=FetchType.LAZY, mappedBy="formations")
    public Set<SuperFormation> getSuperFormations() {
        return this.superFormations;
    }
    
    public void setSuperFormations(Set<SuperFormation> superFormations) {
        this.superFormations = superFormations;
    }

    @Override
    public String toString() {
        return "Formation{" + "libelle=" + libelle + '}';
    }

    
}


